name: bellumeflutter
description: "Facial measurement analysis app in Flutter"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Navigation  
  go_router: ^12.1.3
  
  # Camera & ML
  camera: ^0.10.5+5
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_face_mesh_detection: ^0.4.1
  image: ^4.1.3
  image_picker: ^1.0.4
  
  # Backend
  supabase_flutter: ^2.0.0
  
  # Authentication
  google_sign_in: ^6.1.5
  
  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # UI/UX
  lottie: ^2.7.0
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.1.0
  crypto: ^3.0.3
  fl_chart: 0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/images/
    - icons/
    - models/ 